### ISSUE TITLE
MVP checklist

### ISSUE THREAD

**Issue by robotlolita** [origamitower/furipota#1]
- [x] Plugins
- [x] Simple types (Text, Number, Boolean, Vector, Record)
- [x] Core library
  - [x] Debugging (trace)
  - [x] File System (files, remove, make-directory, write, read, copy)
  - [x] Core (tap, sequence, from-vector, get, at)
- [x] Running definitions
- [x] Procedures
- [x] Listing available definitions when none is given
- [x] `run` should take an arbitrary expression
